services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "1001:8080"
      - "1002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SQL_SERVER=sqlserver
      - SQL_USER=sa
      - SQL_PASSWORD=YourStrong!Passw0rd
    depends_on:
      - postgres 
      - rabbitmq
    volumes:
      - shared-data:/app/wwwroot
  web:
    build: 
        context: src/web
    ports:
      - "1000:1000"
    volumes:
      - .:/web
    command: npm run dev
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: UnifiedAppDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
  document:
    build: 
        context: src/Document
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - shared-data:/app/wwwroot
    command: ["python", "processor2.py"]
volumes:
  sql_data:
  rabbitmq-data: 
  postgres_data:
  shared-data:  